%% Import data from text file.
% Script for importing data from the following text file:
%    C:\Users\elit3\Documents\ft2ddd dmra analysis\selected cells\B06.csv
%% To extend the code to different selected data or a different text file,
% generate a function instead of a script.
% Auto-generated by MATLAB on 2019/09/16 14:24:35
% % you should run this in the directory where the data from cellprofiler 
% was output
% run this for data extracted for dual ktr cell lines
myFolder=pwd;
filePattern = fullfile(myFolder, '*.csv');% what's the file pattern of the input
matFiles = dir(filePattern);

opts = delimitedTextImportOptions("NumVariables", 48);
opts.DataLines = [2, Inf];
opts.Delimiter = ",";
opts.VariableNames = ["ImageImageNumber", "CytoplasmObjectNumber", "ImageMetadata_Column", "ImageMetadata_Column1", "ImageMetadata_FileLocation", "ImageMetadata_Frame", "ImageMetadata_ROI", "ImageMetadata_ROI1", "ImageMetadata_Series", "ImageMetadata_time", "ImageMetadata_wavelength", "CytoplasmIntensity_IntegratedIntensity_DNA", "CytoplasmIntensity_IntegratedIntensity_akt", "CytoplasmIntensity_IntegratedIntensity_erk", "CytoplasmIntensity_MeanIntensity_DNA", "CytoplasmIntensity_MeanIntensity_akt", "CytoplasmIntensity_MeanIntensity_erk", "CytoplasmIntensity_MedianIntensity_DNA", "CytoplasmIntensity_MedianIntensity_akt", "CytoplasmIntensity_MedianIntensity_erk", "CytoplasmIntensity_StdIntensity_DNA", "CytoplasmIntensity_StdIntensity_akt", "CytoplasmIntensity_StdIntensity_erk", "CytoplasmNumber_Object_Number", "NUCIntensity_IntegratedIntensity_DNA", "NUCIntensity_IntegratedIntensity_akt", "NUCIntensity_IntegratedIntensity_erk", "NUCIntensity_MeanIntensity_DNA", "NUCIntensity_MeanIntensity_akt", "NUCIntensity_MeanIntensity_erk", "NUCIntensity_MedianIntensity_DNA", "NUCIntensity_MedianIntensity_akt", "NUCIntensity_MedianIntensity_erk", "NUCIntensity_StdIntensity_DNA", "NUCIntensity_StdIntensity_akt", "NUCIntensity_StdIntensity_erk", "NUCNumber_Object_Number", "NUCTrackObjects_Displacement_20", "NUCTrackObjects_DistanceTraveled_20", "NUCTrackObjects_FinalAge_20", "NUCTrackObjects_IntegratedDistance_20", "NUCTrackObjects_Label_20", "NUCTrackObjects_Lifetime_20", "NUCTrackObjects_Linearity_20", "NUCTrackObjects_ParentImageNumber_20", "NUCTrackObjects_ParentObjectNumber_20", "NUCTrackObjects_TrajectoryX_20", "NUCTrackObjects_TrajectoryY_20"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

for k = 1:length(matFiles)
    baseFileName = matFiles(k).name;
    fullFileName = fullfile(myFolder, baseFileName)
    fprintf(1, 'Now reading %f\n', fullFileName);
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
a{k} = readtable(fullFileName, opts);

end
%% Close the text file.
%% Create output variable
%% Clear temporary variables
save ('a','a')
clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp rawNumericColumns rawStringColumns R catIdx idx;