%% Import data from text file.
% Script for importing data from the following text file:
%    C:\Users\elit3\Documents\ft2ddd dmra analysis\selected cells\B06.csv
%% To extend the code to different selected data or a different text file,
% generate a function instead of a script.
% Auto-generated by MATLAB on 2019/09/16 14:24:35
% % you should run this in the directory where the data from cellprofiler 
% was output
% run this for data extracted for dual ktr cell lines
myFolder=pwd;
filePattern = fullfile(myFolder, 'C*.csv');% what's the file pattern of the input
matFiles = dir(filePattern);
delimiter = ',';
startRow = 2;
endRow = inf;
varname={};
formatSpec = '%f%f%f%f%s%f%f%f%s%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';
for k = 1:length(matFiles)
    baseFileName = matFiles(k).name;
    fullFileName = fullfile(myFolder, baseFileName)
    fprintf(1, 'Now reading %s\n', fullFileName);
    fileID = fopen(fullFileName,'r');
    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end
%% Close the text file.
fclose(fileID);
%% Create output variable
a{k} = table(dataArray{1:end-1}, 'VariableNames', {'ImageImageNumber','CytoplasmObjectNumber','ImageMetadata_Column','ImageMetadata_Frame','ImageMetadata_Row','ImageMetadata_Series','ImageMetadata_Site','ImageMetadata_TP','ImageMetadata_Time','ImageMetadata_Well','CytoplasmIntensity_IntegratedIntensity_DNA','CytoplasmIntensity_IntegratedIntensity_akt','CytoplasmIntensity_IntegratedIntensity_erk','CytoplasmIntensity_MeanIntensity_DNA','CytoplasmIntensity_MeanIntensity_akt','CytoplasmIntensity_MeanIntensity_erk','CytoplasmIntensity_MedianIntensity_DNA','CytoplasmIntensity_MedianIntensity_akt','CytoplasmIntensity_MedianIntensity_erk','CytoplasmIntensity_StdIntensity_DNA','CytoplasmIntensity_StdIntensity_akt','CytoplasmIntensity_StdIntensity_erk','CytoplasmNumber_Object_Number','NUCIntensity_IntegratedIntensity_DNA','NUCIntensity_IntegratedIntensity_akt','NUCIntensity_IntegratedIntensity_erk','NUCIntensity_MeanIntensity_DNA','NUCIntensity_MeanIntensity_akt','NUCIntensity_MeanIntensity_erk','NUCIntensity_MedianIntensity_DNA','NUCIntensity_MedianIntensity_akt','NUCIntensity_MedianIntensity_erk','NUCIntensity_StdIntensity_DNA','NUCIntensity_StdIntensity_akt','NUCIntensity_StdIntensity_erk','NUCNumber_Object_Number','NUCTrackObjects_Displacement_65','NUCTrackObjects_DistanceTraveled_65','NUCTrackObjects_FinalAge_65','NUCTrackObjects_IntegratedDistance_65','NUCTrackObjects_Label_65','NUCTrackObjects_Lifetime_65','NUCTrackObjects_Linearity_65','NUCTrackObjects_ParentImageNumber_65','NUCTrackObjects_ParentObjectNumber_65'});
end
%% Clear temporary variables
save ('c','c')
clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp rawNumericColumns rawStringColumns R catIdx idx;