%% Import data from text file.
% Script for importing data from the following text file:
% Auto-generated by MATLAB on 2019/09/16 14:24:35
% this script works with single reporter data
myFolder=pwd; % the working directory for the CSV that CellProfiler outputs
filePattern = fullfile(myFolder, '*.csv');
matFiles = dir(filePattern);
delimiter = ',';
startRow = 2;
varname={};
formatSpec = '%f%f%f%s%f%f%f%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';
% before we beign we need to make sure the tracking info is right
%match pixels
matchpixels=50; % DEFINE this before starting
matchpixels_STR=num2str(matchpixels);
parfor k = 1:length(matFiles)

baseFileName = matFiles(k).name;
  fullFileName = fullfile(myFolder, baseFileName)
  fprintf(1, 'Now reading %s\n', fullFileName);
fileID = fopen(fullFileName,'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
%% Close the text file.
fclose(fileID);
%% Replace non-numeric cells with NaN
a{k} =table(dataArray{1:end-1}, 'VariableNames', {'ImageImageNumber','CytoplasmObjectNumber','ImageMetadata_Column','ImageMetadata_Row','ImageMetadata_Series','ImageMetadata_Site','ImageMetadata_TP','ImageMetadata_Well','CytoplasmIntensity_IntegratedIntensity_DNA','CytoplasmIntensity_IntegratedIntensity_ktr','CytoplasmIntensity_MeanIntensity_DNA','CytoplasmIntensity_MeanIntensity_ktr','CytoplasmIntensity_MedianIntensity_DNA','CytoplasmIntensity_MedianIntensity_ktr','CytoplasmIntensity_StdIntensity_DNA','CytoplasmIntensity_StdIntensity_ktr','CytoplasmNumber_Object_Number','NUCIntensity_IntegratedIntensity_DNA','NUCIntensity_IntegratedIntensity_DNA1','NUCIntensity_IntegratedIntensity_ktr','NUCIntensity_MeanIntensity_DNA','NUCIntensity_MeanIntensity_DNA1','NUCIntensity_MeanIntensity_ktr','NUCIntensity_MedianIntensity_DNA','NUCIntensity_MedianIntensity_DNA1','NUCIntensity_MedianIntensity_ktr','NUCIntensity_StdIntensity_DNA','NUCIntensity_StdIntensity_DNA1','NUCIntensity_StdIntensity_ktr',...,
    strcat('NUCTrackObjects_FinalAge_',matchpixels_STR),strcat('NUCTrackObjects_Label_',matchpixels_STR),strcat('NUCTrackObjects_Lifetime_',matchpixels_STR),strcat('NUCTrackObjects_ParentImageNumber_',matchpixels_STR),strcat('NUCTrackObjects_ParentObjectNumber_',matchpixels_STR)});
end
save ('a','a')